version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: TODO
      DB_USER: postgres
      DB_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: TODO
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
